# Generated by Django 6.0.2 on 2026-02-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_address_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
