# Generated by Django 6.0.2 on 2026-02-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_address_user_adress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="description",
            field=models.TextField(
                blank=True, help_text="모여서 하는 활동에 대한 간단한 설명"
            ),
        ),
    ]
