# Generated by Django 6.0.2 on 2026-02-13 01:04

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_meeting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="meeting_id",
            field=models.CharField(
                default=main.models.generate_meeting_code,
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
