# Generated by Django 6.0.2 on 2026-02-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_meeting_meeting_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                max_length=10,
            ),
        ),
    ]
