# Generated by Django 6.0.2 on 2026-02-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_meetingmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], max_length=10),
        ),
    ]
