# Generated by Django 6.0.2 on 2026-02-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_meetingmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
