# Generated by Django 6.0.2 on 2026-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_boardimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardpost",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
