# Generated by Django 6.0.2 on 2026-03-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_boardpost_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="main.boardcomment",
            ),
        ),
    ]
