# Generated by Django 6.0.2 on 2026-03-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_boardcomment_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fincategory',
            name='uq_fin_category',
        ),
        migrations.AlterField(
            model_name='fintransaction',
            name='category',
            field=models.CharField(default='기타', max_length=50),
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='idx_receipt_meeting_created',
        ),
        migrations.RemoveField(
            model_name='fincategory',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
        migrations.DeleteModel(
            name='FinCategory',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
