# Generated by Django 6.0.2 on 2026-03-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_fintransaction_receipt_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinAttachment',
        ),
    ]
