"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&xiyb5yk*g^6ol(2@qfx=0vl#_javj-n&(uyo%fwjw#sl_r3vn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['lean-blotchiest-postvocalically.ngrok-free.dev', 'localhost', '127.0.0.1', '0.0.0.0']
CSRF_TRUSTED_ORIGINS = ['https://lean-blotchiest-postvocalically.ngrok-free.dev', 'http://lean-blotchiest-postvocalically.ngrok-free.dev']

# Ngrok/Proxy settings
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'corsheaders',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.naver',
    'allauth.socialaccount.providers.kakao',
]

AUTH_USER_MODEL = "main.User"


SITE_ID = 1

# 소셜 로그인 후 리다이렉트 경로 등 설정
SOCIALACCOUNT_PROVIDERS = {
    'naver': {
        # 'APP': {
        #     'client_id': '',
        #     'secret': '',
        #     'key': ''
        # }
    },
    'kakao': {
        # 'APP': {
        #     'client_id': '',
        #     'secret': '',
        #     'key': ''
        # }
    },
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# 로그인 후 리다이렉트할 주소 (예: /main/)
LOGIN_REDIRECT_URL = '/main'
# 로그아웃 후 리다이렉트할 주소
ACCOUNT_LOGOUT_REDIRECT_URL = '/login'

# 1. 로그인 수단 설정 (중괄호 세트 형태)
ACCOUNT_LOGIN_METHODS = {'email'}

# 2. 가입 시 받을 필드 (리스트 형태)
ACCOUNT_SIGNUP_FIELDS = ['email']

# 3. 기타 필수 설정
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "none" # 또는 "mandatory" (지누님 선택)

# 소셜 관련
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ERROR_REDIRECT_URL = '/login'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True # 개발 환경용 (배포 시 특정 도메인만 허용해야 함)


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'legacy' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'legacy' / 'static',
]

# 배포 시 파일들을 한곳으로 모으는 경로 (보통 루트의 static_root 등)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 배포(Deployment) 시 모든 static 파일을 한곳으로 모을 경로 (시연 시엔 필수는 아님)
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # 기본값: 브라우저 닫으면 세션 만료
SESSION_SAVE_EVERY_REQUEST = True        # 매 요청마다 세션 저장
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# 모바일 및 HTTPS(ngrok) 환경을 위한 보안 설정
# ngrok을 통해 접속하므로 HTTPS 환경임에 따라 Secure 플래그 활성화
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
